name: Check website links

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  check-links:
    name: Check links
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site:
         - name: DAKLabb
           url: daklabb.dev
         - name: PingThings
           url: pingthings.io
         - name: Sayari
           url: sayari.com
      fail-fast: false
    steps:
      - name: Check ${{ matrix.site.name }} Links
        uses: DAKLabb/check-links@v0.0.1
        with:
          url: ${{ matrix.site.url }}
          site-name: ${{ matrix.site.name }}
          report-name: ${{ matrix.site.name }} Link report
          check-external: true
          include-warnings: false

