name: Check website links

on:

  push:
    branches:
      - "**"
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  check-links:
    name: Check links
    runs-on: ubuntu-latest
    strategy:
      matrix:
        site:
         - name: DAKLabb
           url: "daklabb.dev"
      fail-fast: false
    steps:
      - name: Check ${{ matrix.site.name }} Links
        uses: DAKLabb/check-links@v0.0.1-alpha
        with:
          url: daklabb.dev 